### PR TITLE
#58: 'digits' option added to passwordPolicy map in UpdateRealmAction

### PR DESCRIPTION
**Pull request by aberg09**
Hi,
I had apparently overlooked the digits option for password policy in the UpdateRealmAction. I have added it here now.

### CODE REVIEW

**Comment by klg71** [comment]
Hey @aberg09 thanks for your contribution :)

**Comment by klg71** [comment]
Released with version 0.2.54 could you please check it? :)

**Comment by aberg09** [comment]
> Released with version 0.2.54 could you please check it? :)

I have problems downloading the fat jar for this version (I can download it from github but when I try to use it I get 'Invalid or corrupt jarfile'). I have tried older versions (53-49) and there the same happens. The most recent version that runs is 48.
Indeed I also see that 48 is the version offered on https://github.com/mayope/keycloakmigration/releases.

The download URL I am using is
https://github.com/mayope/keycloakmigration/releases/download/[version]/keycloakmigration-[version]-fat.jar

**Comment by aberg09** [comment]
And thank you, as always, for your quick reply :)

**Comment by klg71** [comment]
Sry I forgot to draft the release. It should be available here now: https://github.com/mayope/keycloakmigration/releases/tag/0.2.54

**Comment by aberg09** [comment]
It works now. Thanks one more time :) !

**Pull request merged**
