### PR TITLE
#58: Support for password policy in realm update

### PR DESCRIPTION
**Pull request by aberg09**
Same story here.

There are only the changes Realm.kt and UpdateRealmAction.kt sofar.
I have 1000+files in the docs and docsbuild directories that got changed due to the docuemtnation autogeneration. I guess something is wring with the gitingore file here and those should no tbe part of the commit?

I have tested manually.
I was not sure whether (or where) to add automated tests. Please provide some guidance here.

### CODE REVIEW

**Comment by klg71** [comment]
Hey aberg :) Code looks good thanks for your contribution <3
We could however make our api more convenient to use if we would take a dictionary as input for the action and not a raw string.
E.g.:
```
updateRealm:
  passwordPolicy:
    - name: digits
      value: 2
    - name: passwordBlacklist
      value: test
```
We could then concatenate the list in the UpdateRealmAction. This is just a suggestion and I will also merge this request if you don't want to implement it that way. :)

**Comment by aberg09** [comment]
> Hey aberg :) Code looks good thanks for your contribution <3 We could however make our api more convenient to use if we would take a dictionary as input for the action and not a raw string. E.g.:
> 
> ```
> updateRealm:
>   passwordPolicy:
>     - name: digits
>       value: 2
>     - name: passwordBlacklist
>       value: test
> ```
> 
> We could then concatenate the list in the UpdateRealmAction. This is just a suggestion and I will also merge this request if you don't want to implement it that way. :)

I agree it would be much nicer to have it that way. I will see if I can implement it without too much effort.

**Comment by aberg09** [comment]
Hi again,
I have made the changes you suggested and added a test.
The most recent master branch is merged in and docs are regenerated.

I hope everything is in place :)

**Review by klg71 — APPROVED** [review]
:)

**Comment by aberg09** [comment]
Hello again,
I just realized I forgot do include the password option that allows to specify the number of digits.
I open a new pull request where I add that one value (#71).
Sorry for the inconvenience.

**Pull request merged**
