### PR TITLE
fix(identityProvider): make displayName optional

### PR DESCRIPTION
**Pull request by MrDeerly**
Hey there! 

This PR fixes a bug where identityProviders without a displayName can't be updated (and probably not deleted). 

The field is optional by keycloak (e.g. for so called "social identity providers" like LinkedIn) and should therefore also be optional internally.

**Reproduction:**

1. Create an identityProvider without displayName field (e.g. LinkedIn).
2. Update the identityProvider:

```yaml
  - updateIdentityProvider:
      alias: google
      config:
        clientId: test
        clientSecret: test
```

Results in: 

`Exception in thread "main" feign.FeignException: Instantiation of [simple type, class de.klg71.keycloakmigration.keycloakapi.model.IdentityProvider] value failed for JSON property displayName due to missing (therefore NULL) value for creator parameter displayName which is a non-nullable type`

### CODE REVIEW

**Comment by MrDeerly** [comment]
Existing tests shouldn't be affected at all

**Comment by klg71** [comment]
Hey @MrDeerly  thanks for another Merge Request :). Do we need to update the documentation on this field?

**Comment by MrDeerly** [comment]
Sorry for the delays.. adjusted all tests :)

**Comment by MrDeerly** [comment]
just checked, no adjustments needed!

**Pull request merged**
