### PR TITLE
feat: add ability to assign roles to ClientScopes

### PR DESCRIPTION
**Pull request by MrDeerly**
Hey there!

This is still wip.. the basic implementation is done and (manually) tested. I just need to add docs, and tests for it. 

If you want you can already take a look at the basic implementation. I'll update the MR once the rest is done.

### CODE REVIEW

**Comment by klg71** [comment]
Hey MrDeerly,

Thanks for contributing to this project :) The MR looks fine so far if you could provide the documentation and an IntegrationTest nothing will prevent me from merging this.

Best Regards
klg71

**Comment by MrDeerly** [comment]
Hey, no worries... thanks for the great tool! 

I've added a few tests and adjusted the docs. TBH i don't know if i've missed something for the docs, if so just let me know!

**Comment by MrDeerly** [comment]
Ahh and for the next release: I'll add another MR today or tomorrow! 

_Grüße von Deutschland nach Deutschland! :)_

**Comment by klg71** [comment]
Ok then I will merge this one but will wait with the release for your next Merge Request :)

**Review by klg71 — APPROVED** [review]

**Comment by klg71** [comment]
Released with version: https://github.com/mayope/keycloakmigration/releases/tag/0.2.33

**Pull request merged**
