### PR TITLE
Feature/client update clientauthenticatortype

### PR DESCRIPTION
**Pull request by IngoStrauch2020**
Implements #83

### CODE REVIEW

**Comment by IngoStrauch2020** [comment]
Is there a way to do some consistency checks? Like only allowing certain values for `clientAuthenticatorType`. Or only allowing to update this property for non-public clients.

**Comment by klg71** [comment]
You could just add some conditions in the `execute` method.
```
  if (clientAuthenticatorType!= null && clientAuthenticatorType!="client-jwt") {
            throw MigrationException("Unkown client authenticator type")
  }
  if (oldClient.publicClient==true) {
            throw MigrationException("not supported for public clients")
  }
```

**Comment by klg71** [comment]
Looks good! Thanks for your pull request <3

**Comment by IngoStrauch2020** [comment]
You're welcome. :-) But then, it's us who want to use that feature (and likely other teams at my company, too). ;-)

**Pull request merged**
